version: "3.7"

services:
  nginx:
    image: nginx:1.23
    volumes:
      - ./:/var/www
      - ./docker/nginx/crm.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "12310:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - general
  fpm:
    build:
      context: 'docker/phpfpm'
    working_dir: /var/www/
    networks:
      - general
    volumes:
      - ./:/var/www
    user: 1000:1000
  db:
    image: mysql:8
    command: "--default-authentication-plugin=mysql_native_password" #--innodb_use_native_aio=0
    # user: 1000:1000
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
      MYSQL_USER: test
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - "33061:3306"
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    networks:
      - general
  adminer:
    image: adminer
    networks:
      - general
    ports:
      - "12311:8080"

networks:
  general:
    driver: bridge
